<a href="https://colab.research.google.com/github/khanguyen38/CS-5130-Applied-Programming-and-Data-Processing-for-AI/blob/main/CS_5130_Week_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
################# Cell 0 — Setup (safe to re-run anytime)
import numpy as np

# Format NumPy print: no scientific notation, 4 decimals
np.set_printoptions(suppress=True, precision=4)

# Fix random seed for reproducible results
np.random.seed(42)
print("Setup complete ✓")

Setup complete ✓


In [25]:
################### Cell 1 — Creating vectors (NumPy arrays)

# Format NumPy print: no scientific notation, 4 decimals
np.set_printoptions(suppress=True, precision=4)

# From Python list
vec1 = np.array([1, 2, 3, 4, 5])
print("vec1:", vec1)

# From list + explicit dtype (float32 saves memory vs float64)
vec2 = np.array([1, 2, 3], dtype=np.float32)
print("vec2 (float32):", vec2, vec2.dtype)

# Ranges
vec3 = np.arange(0, 10, 2)      # [0,2,4,6,8]
vec4 = np.linspace(0, 1, 5)     # 5 evenly spaced points in [0,1]
print("vec3 (arange):", vec3)
print("vec4 (linspace):", vec4)

vec1: [1 2 3 4 5]
vec2 (float32): [1. 2. 3.] float32
vec3 (arange): [0 2 4 6 8]
vec4 (linspace): [0.   0.25 0.5  0.75 1.  ]


In [37]:

############# Cell 2 — Special & random vectors
zeros = np.zeros(5)
ones = np.ones(3)
full = np.full(4, 3.14)
eye_like = np.eye(1, 5)[0]     # "identity-like" 1x5 row → take row 0
eye_like2 =np.eye(4, 5) #
print("zeros:", zeros)
print("ones:", ones)
print("full:", full)
print("eye_like:", eye_like)
print("eye_like2:", eye_like2)

print("random uniform [0,1):", np.random.random(3))
print("uniform(-1,1):", np.random.uniform(-1, 1, 3))
print("standard normal:", np.random.randn(3))
print("randint [0,10):", np.random.randint(0, 10, 3))

zeros: [0. 0. 0. 0. 0.]
ones: [1. 1. 1.]
full: [3.14 3.14 3.14 3.14]
eye_like: [1. 0. 0. 0. 0.]
eye_like2: [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
random uniform [0,1): [0.3745 0.9507 0.732 ]
uniform(-1,1): [ 0.1973 -0.688  -0.688 ]
standard normal: [ 1.5792  0.7674 -0.4695]
randint [0,10): [4 0 9]


In [3]:
########### Cell 3 — Element-wise ops, scalars, ufuncs
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print("a + b:", a + b)               # element-wise add
print("a * b:", a * b)               # element-wise multiply
print("b / a:", b / a)               # element-wise divide
print("a * 10:", a * 10)             # scalar broadcast

print("sqrt(a):", np.sqrt(a))
print("log(a):", np.log(a))
print("exp(a):", np.exp(a))

a + b: [ 6  8 10 12]
a * b: [ 5 12 21 32]
b / a: [5.         3.         2.33333333 2.        ]
a * 10: [10 20 30 40]
sqrt(a): [1.         1.41421356 1.73205081 2.        ]
log(a): [0.         0.69314718 1.09861229 1.38629436]
exp(a): [ 2.71828183  7.3890561  20.08553692 54.59815003]


In [14]:
###  Random Vector is crucial for ML Algoritms
# Set seed for reproducibility
np.random.seed(42)

# Uniform distribution [0, 1)
uniform = np.random.random(5)

# Uniform in custom range
uniform_range = np.random.uniform(-1, 1, 5)

# Normal distribution (mean=0, std=1)
normal = np.random.randn(5)

# Normal with custom parameters
normal_custom = np.random.normal(loc=100, scale=15, size=5)

# Random integers
integers = np.random.randint(0, 10, size=5)
# -------------------------------

print("uniform [0,1):", uniform)
print("uniform_range [-1,1):", uniform_range)
print("normal N(0,1):", normal)
print("normal_custom N(100,15^2):", normal_custom)
print("integers [0,10):", integers)

uniform [0,1): [0.3745 0.9507 0.732  0.5987 0.156 ]
uniform_range [-1,1): [-0.688  -0.8838  0.7324  0.2022  0.4161]
normal N(0,1): [-0.4695  0.5426 -0.4634 -0.4657  0.242 ]
normal_custom N(100,15^2): [ 71.3008  74.1262  91.5657  84.8075 104.7137]
integers [0,10): [2 6 3 8 2]


In [21]:
####### Cell 4 — Dot product, norms, normalization.

import numpy as np
np.set_printoptions(suppress=True, precision=4)

  #Dot Product
u = np.array([[1, 2, 3],[2,3,4]])
v = np.array([4, 5, 6])
print("u @ v (dot):", u @ v)         # 32
print("u @ v (dot):", u.dot(v))
print("u @ v (dot):", np.dot(u,v))

  #Magnitude (Norm) do dai or kich thuoc cua vector

w = np.array([3., 4.])

# L2 norm (euclidean norm - khoang cach Euclid)
print("||w||_2:", np.linalg.norm(w))               # 5.0 ( dinh ly pythagoras : Cách tính quen thuộc nhất – giống như đo cạnh huyền trong tam giác vuông.)

#L1 norm (Manhattan norm) – khoảng cách Manhattan
print("||w||_1:", np.linalg.norm(w, 1))            # 7.0 ( chỉ đi ngang và dọc, không đi chéo.)

#L∞ norm (chuẩn vô cùng)
print("||w||_inf:", np.linalg.norm(w, np.inf))     # 4.0 ( chỉ quan tâm bước dài nhất theo một trục, chiều dài lớn nhất của vector trên một trục (ở đây trục y = 4).)

#Vector đơn vị (unit vector)
w_unit = w / np.linalg.norm(w) #vector ngắn lại thành độ dài 1, nhưng cùng hướng.Khi chia cho 5, ta được vector cùng hướng nhưng độ dài = 1, [3., 4.] -> [3/5 4/5] = [0.6 0.8]
print("w_unit:", w_unit, "norm:", np.linalg.norm(w_unit))

u @ v (dot): [32 47]
u @ v (dot): [32 47]
u @ v (dot): [32 47]
||w||_2: 5.0
||w||_1: 7.0
||w||_inf: 4.0
w_unit: [0.6 0.8] norm: 1.0


In [25]:
####### Boadcasting essentials
# cách NumPy tự mở rộng (copy ảo) kích thước mảng để các toán tử (+, -, *, /, …) có thể áp dụng phần tử theo phần tử (element-wise).
#Nếu hai mảng không cùng shape, NumPy sẽ cố “kéo giãn” (broadcast) chúng để khớp với nhau.


# Scalar + vector
vec = np.array([1, 2, 3])
print("vec + 10:", vec + 10)

# Column vs row → creates matrix by broadcasting
col = np.array([[1], [2], [3]])   # shape (3,1) Here you are creating a 2D NumPy array.
row = np.array([10, 20, 30])      # shape (3,) behaves like (1,3)

print("col:",col)
print("row:",row)
print("col + row:\n", col + row)

vec + 10: [11 12 13]
col: [[1]
 [2]
 [3]]
row: [10 20 30]
col + row:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


In [1]:
######Cell 6 — Practical mini-functions (scaling, standardize, cosine, distance)

import numpy as np
np.set_printoptions(suppress=True, precision=4)

# Hàm min_max_scale: Dùng để đưa dữ liệu về khoảng [0,1].
def min_max_scale(vec):
    return (vec - vec.min()) / (vec.max() - vec.min())

# Hàm standardize: dữ liệu được chuẩn hóa về trung bình = 0, độ lệch chuẩn = 1.
def standardize(vec):
    return (vec - vec.mean()) / vec.std()

# Hàm cosine_similarity: đo độ giống nhau về hướng giữa 2 vector.Kết quả trong [-1,1].
# a @ b = tích vô hướng (dot product).
#1  = giống hệt hướng, 0 = vuông góc, -1 = ngược hướng.
def cosine_similarity(a, b):
    denom = np.linalg.norm(a) * np.linalg.norm(b)
    return 0.0 if denom == 0 else float((a @ b) / denom)

# Hàm euclidean_distance: đo độ xa tuyệt đối giữa hai vector
def euclidean_distance(a, b):
    return float(np.linalg.norm(a - b))

ages = np.array([22, 25, 30, 45, 67])
print("min_max_scale(ages):", min_max_scale(ages))
print("standardize(ages):", standardize(ages))

user1 = np.array([5, 3, 0, 1])
user2 = np.array([4, 0, 0, 1])
user3 = np.array([1, 1, 5, 4])
print("cos(user1,user2):", cosine_similarity(user1, user2))  # cos ~ 0.97 → rất giống nhau


print("cos(user1,user3):", cosine_similarity(user1, user3))  # ~0.38
print("dist(user1,user2):", euclidean_distance(user1, user2))

min_max_scale(ages): [0.     0.0667 0.1778 0.5111 1.    ]
standardize(ages): [-0.9515 -0.7708 -0.4697  0.4336  1.7584]
cos(user1,user2): 0.8609160647753271
cos(user1,user3): 0.30932355733588024
dist(user1,user2): 3.1622776601683795


In [2]:
####### Cell 7 — Matrices: creation, axes, reshaping

import numpy as np
np.set_printoptions(suppress=True, precision=4)

A = np.array([[1, 2, 3],
              [4, 5, 6]])
print("A:\n", A)

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
A2 = np.vstack([v1, v2])
print("np.vstack([v1,v2]):\n", A2)

x = np.arange(12)
X = x.reshape(3, 4)
print("X (reshape 3x4):\n", X)

data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print("data.sum(axis=0) [col sums]:", data.sum(axis=0)) # axis=0 = dọc xuống (cột).
print("data.sum(axis=1) [row sums]:", data.sum(axis=1)) # axis=1 = ngang qua (hàng)
print("data.sum() total:", data.sum())

A:
 [[1 2 3]
 [4 5 6]]
np.vstack([v1,v2]):
 [[1 2 3]
 [4 5 6]]
X (reshape 3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
data.sum(axis=0) [col sums]: [12 15 18]
data.sum(axis=1) [row sums]: [ 6 15 24]
data.sum() total: 45


In [3]:
#### Cell 8 — Per-feature normalization (2D, broadcasting)
import numpy as np
np.set_printoptions(suppress=True, precision=4)

D = np.array([[1., 2., 3.],
              [4., 5., 6.],
              [7., 8., 9.]])
means = D.mean(axis=0) # column's mean axis=0
centered = D - means                 # subtract per-column mean #Centering (D - means): làm mỗi cột có mean = 0.
print("means:", means)
print("centered:\n", centered)

def normalize_features(data2d): #Normalization (min-max): co dãn mỗi cột về trong khoảng [0,1].
    mins = data2d.min(axis=0)
    maxs = data2d.max(axis=0)
    return (data2d - mins) / (maxs - mins)

print("normalize_features(D):\n", normalize_features(D))

means: [4. 5. 6.]
centered:
 [[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]
normalize_features(D):
 [[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


In [4]:
####### Cell 9 — * (element-wise) vs @ (matrix multiply)
import numpy as np
np.set_printoptions(suppress=True, precision=4)

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("A * B (element-wise):\n", A * B)
print("A @ B (matrix product):\n", A @ B)

A * B (element-wise):
 [[ 5 12]
 [21 32]]
A @ B (matrix product):
 [[19 22]
 [43 50]]


In [5]:
######### Cell 10 — Views vs copies (mutation gotcha)
import numpy as np
np.set_printoptions(suppress=True, precision=4)

arr = np.array([1, 2, 3, 4])
ref = arr            # shares memory with arr , chỉ thêm tên gọi khác → cùng 1 dữ liệu.
cpy = arr.copy()     # independent copy ,tạo dữ liệu mới, độc lập.

ref[0] = 99
print("arr after ref[0]=99:", arr)  # changed!
cpy[0] = 88
print("arr after cpy[0]=88:", arr)  # unchanged by copy

arr after ref[0]=99: [99  2  3  4]
arr after cpy[0]=88: [99  2  3  4]


In [6]:
### Cell 11 — Linear transformations: scaling, rotation, projection
# Đây là 3 phép biến đổi hình học cơ bản bằng ma trận trong 2D: co giãn (scaling), xoay (rotation), và chiếu lên đường thẳng (projection)
import numpy as np
np.set_printoptions(suppress=True, precision=4)

# (a) Scaling in 2D
sx, sy = 2.0, 0.5
S = np.array([[sx, 0. ],
              [0. , sy]])
p = np.array([3., 4.])
print("Scaling S @ p:", S @ p)      # -> [6., 2.]

# (b) Rotation in 2D
def R2(theta):
    c, s = np.cos(theta), np.sin(theta)
    return np.array([[c, -s],
                     [s,  c]])

theta = np.pi / 4  # 45 degrees
R = R2(theta)
p0 = np.array([1., 0.])
print("Rotation R(45°) @ [1,0]:", R @ p0)

# (c) Projection onto a line (2D)
def project_onto_line(points, direction):
    u = direction / np.linalg.norm(direction)  # unit direction # chuẩn hóa -> vector đơn vị
    P = np.outer(u, u)                         # projection matrix = uu^T
    return points @ P.T

pts = np.array([[2., 1.],
                [3., 5.],
                [-1., 2.]])
diag = np.array([1., 1.])  # y = x direction
print("Project pts onto y=x:\n", project_onto_line(pts, diag))


Scaling S @ p: [6. 2.]
Rotation R(45°) @ [1,0]: [0.7071 0.7071]
Project pts onto y=x:
 [[1.5 1.5]
 [4.  4. ]
 [0.5 0.5]]


In [10]:
##### Cell 12 — Performance: vectorization vs loop

import numpy as np, time
np.set_printoptions(suppress=True, precision=4)

N = 200_000
a = np.random.randn(N) # mean =0, std =1
b = np.random.randn(N)

t0 = time.perf_counter()
res_loop = [a[i] + b[i] for i in range(N)]
t1 = time.perf_counter()

t2 = time.perf_counter()
res_vec = a + b
t3 = time.perf_counter()

loop_s = t1 - t0
vec_s  = t3 - t2
speedup = loop_s / vec_s if vec_s > 0 else np.inf  #tính speedup = loop_s / vec_s (tốc độ nhanh hơn bao nhiêu lần).gán speedup = np.inf (vô cùng, nghĩa là nhanh vô hạn).

print(f"Loop (s): {loop_s:.4f}")
print(f"Vectorized (s): {vec_s:.4f}")
print(f"Speedup: {speedup:.1f}x")

Loop (s): 0.0758
Vectorized (s): 0.0009
Speedup: 87.8x


In [9]:
print(np.random.randn(100))

[-0.4236  0.8267 -1.7913  0.479  -0.0518 -1.4333 -0.6983 -0.6964  0.9481
 -1.2081  0.2097  1.1667  1.0719 -0.0519  0.6895  0.9973 -0.1362  1.6911
  0.3013 -0.1608 -0.117   0.1024  0.1749 -0.8704  0.2397 -0.8274  0.2661
 -0.1487 -2.3118 -0.5742 -0.9407  1.5172  0.2509 -2.122  -1.385   0.7755
  0.8032 -0.6218 -0.7948 -0.3648  0.9958  1.2142  0.5459 -1.1693 -1.1631
  0.8521 -0.4242  0.1922  1.1326  0.2841 -0.0525  0.1053  0.3407 -0.8156
 -2.1633 -0.5543 -1.0535 -0.1445  0.3804 -0.4837  0.1337  0.2323 -1.4515
 -1.988   1.1593  0.6569  1.2028  1.7655  0.3624 -1.3815 -1.6437  2.0996
 -0.4992 -1.8264 -0.3138 -2.5269 -0.8533  0.4186  0.3148 -1.1035  1.1654
  0.4664  2.2263 -0.1644  1.3649 -0.2913  2.2696  0.2499  0.1701 -1.8931
  0.0203 -0.3272 -0.397  -0.3953  1.1198  0.1835  0.1227 -0.5111 -2.0288
 -0.176 ]
